test: update action

diff --git a/.github/workflows/migrate-to-prod-merge.yml b/.github/workflows/migrate-to-prod-merge.yml
--- a/.github/workflows/migrate-to-prod-merge.yml
+++ b/.github/workflows/migrate-to-prod-merge.yml
@@ -17,11 +17,11 @@ jobs:
     if: github.event.pull_request.merged == true # Ensure the PR was merged
 
     steps:
-      # - name: Install PostgreSQL
-      #   run: |
-      #     sudo apt update
-      #     yes '' | sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
-      #     sudo apt install -y postgresql-${{ env.PG_VERSION }}
+      - name: Install PostgreSQL
+        run: |
+          sudo apt update
+          yes '' | sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
+          sudo apt install -y postgresql-${{ env.PG_VERSION }}
 
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -34,22 +34,22 @@ jobs:
           echo "Changed files:"
           cat migration_files.txt
 
-      # - name: Apply migrations
-      #   run: |
-      #     while IFS= read -r file; do
-      #       if [ ! -f "$file" ]; then
-      #         echo "$file does not exist"
-      #         continue
-      #       fi
+      - name: Apply migrations
+        run: |
+          while IFS= read -r file; do
+            if [ ! -f "$file" ]; then
+              echo "$file does not exist"
+              continue
+            fi
 
-      #       if [[ "$file" != *.sql ]]; then
-      #         echo "$file is not a SQL file"
-      #         continue
-      #       fi
+            if [[ "$file" != *.sql ]]; then
+              echo "$file is not a SQL file"
+              continue
+            fi
 
-      #       echo "Processing $file"
-      #       if ! /usr/lib/postgresql/${{ env.PG_VERSION }}/bin/psql "${{ env.PROD_DATABASE_URL }}" < "$file"; then
-      #         echo "Error applying $file"
-      #         exit 1
-      #       fi
-      #     done < migration_files.txt
+            echo "Processing $file"
+            if ! /usr/lib/postgresql/${{ env.PG_VERSION }}/bin/psql "${{ env.PROD_DATABASE_URL }}" < "$file"; then
+              echo "Error applying $file"
+              exit 1
+            fi
+          done < migration_files.txt
